### ISSUE TITLE
beta = 0 behaviour

### ISSUE THREAD

**Issue by newling** [ROCmSoftwarePlatform/MIOpenGEMM#13]
Currently `beta = 0` is not handled as a special case. It should be. When `beta = 0`, the operation should be `C = alpha*A*B` and not `C =  alpha*A*B + beta*C`, which is different when nans are present.

**Comment by rgiduthuri** [comment]
FYI. We are seeing nans appear randomly for some convolutions. This could explain one possible cause.

**Comment by newling** [comment]
This has been corrected in commit 62e247cbfb7b57f78fb0eb14d824d11c9cc913bf on master. I hope this fixes the nans in the convolutions.

**Comment by dagamayank** [comment]
Works on my end. Thanks.
