### ISSUE TITLE
Warning: cast from 'const __global float *' to 'const __global float2 *'

### ISSUE THREAD

**Issue by newling** [ROCmSoftwarePlatform/MIOpenGEMM#14]
Some kernels give a cast-align warning,

```
cast from 'const __global float *' to 'const __global float2 *'
increases required alignment from 4 to 8 [-Werror,-Wcast-align]
const __global TVFLOATA * a_vec = (const __global TVFLOATA * )a;
```

Is this something to be concerned about? I see in MIOpen that this warning is suppressed ([line](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/a7d480b9084d6e754f3939202d0f42e1dbb5bfad/src/kernel_warnings.cpp#L44)).

Is this only relevant for non-homogeneous datatypes? I don't know, could someone with more experience please comment here.

**Comment by dagamayank** [comment]
@alyashev - Can you comment here.

**Comment by alyashev** [comment]
It's OK. our HW does not need a particular alignment to handle a double float. the only concern is with out a care it might step OOB.

**Comment by newling** [comment]
@alyashev -  thanks a lot for this information.
