### ISSUE TITLE
How much can MIOpenGEMM bring performance promotion compared with clBLAS?

### ISSUE THREAD

**Issue by mz24cn** [ROCmSoftwarePlatform/MIOpenGEMM#16]
I am comparing several OpenCL libraries performance on gemm function (source opened at https://github.com/mz24cn/gemm_optimization). clBLAS shows very nice performance comapred with cublas, clblast, MKL.

I wanna know whether MIOpenGEMM can bring better performance than clBLAS? Especially for old device such as R9 295X2 and other vendor's devices.

**Comment by newling** [comment]
Partially discussed in issue https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/issues/16 . I have not run any benchmarks with clBLAS.
