### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by mz24cn** [ROCmSoftwarePlatform/MIOpenGEMM#17]
I successfully compiled libmiopengemm.dll in Windows by MinGW64, while failed to compile in MSVC 2015. I guess MSVC is not supported currently, right?

**Comment by mz24cn** [comment]
In Windows and MinGW64, generated program throws runtime error:
MIOpenGEMM   failed to compile kernel in Programs::update :                                                    ERROR (1)
MIOpenGEMM   Reporting an opencl error (MIOpenGEMM-hash: `building program in set_program_and_kernel') which   ERROR (2)
MIOpenGEMM    returned with cl_int -11 from function CL Compilation failed:                                    ERROR (3)
MIOpenGEMM   (buffer size = 94)  (buffer substring  : Error in processing command line: Don't understand com   ERROR (4)
MIOpenGEMM   mand line argument "-Wf,-Weverything"!

**Comment by newling** [comment]
As far as I know there has been no testing on Windows, but I stand to be corrected. The specific error you are seeing can be eliminated by commenting out from [line 100](
https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/blob/ecda47577d9f2b7ea46d20457a4f79428e4e5e69/miopengemm/src/programs.cpp#L100) to [line 105](https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/blob/ecda47577d9f2b7ea46d20457a4f79428e4e5e69/miopengemm/src/programs.cpp#L105) of src/programs.cpp

**Comment by mz24cn** [comment]
Test result report:
**1, On Windows, clBLAS is still much faster than miopengemm on AMD device (R9 295X2).**
PS D:\CPP\gemm_optimization\Release> .\gemm_optimization.exe /1 :verify 1 :miopen 1 :step 8
Compared with MIOpenGemm, Verification enabled, Parallel disabled
[1] Hawaii  (kernels build: 448ms)
M=2048  N=512   K=2048  times=9         Time=283.021/31.446, 394.021/43.78ms    SpeedUp=0.718273        delta=0
M=2048  N=512   K=256   times=101       Time=418.029/4.138, 173.01/1.712ms      SpeedUp=2.41706         delta=0
M=2048  N=512   K=32    times=360       Time=279.013/0.775, 182.01/0.505ms      SpeedUp=1.53465         delta=0
M=2048  N=64    K=2048  times=101       Time=541.034/5.356, 208.01/2.059ms      SpeedUp=2.60126         delta=0
M=2048  N=64    K=256   times=360       Time=275.013/0.763, 187.01/0.519ms      SpeedUp=1.47013         delta=0
M=2048  N=64    K=32    times=1091      Time=207.011/0.189, 171.008/0.156ms     SpeedUp=1.21154         delta=0
M=256   N=512   K=2048  times=101       Time=513.032/5.079, 281.015/2.782ms     SpeedUp=1.82566         delta=0
M=256   N=512   K=256   times=360       Time=245.012/0.68, 159.009/0.441ms      SpeedUp=1.54195         delta=0
M=256   N=512   K=32    times=1091      Time=225.011/0.206, 144.006/0.131ms     SpeedUp=1.57252         delta=0
M=256   N=64    K=2048  times=360       Time=949.058/2.636, 201.009/0.558ms     SpeedUp=4.72401         delta=0
M=256   N=64    K=256   times=1091      Time=428.023/0.392, 203.011/0.186ms     SpeedUp=2.10753         delta=0
M=256   N=64    K=32    times=3160      Time=398.023/0.125, 148.006/0.046ms     SpeedUp=2.71739         delta=0
M=32    N=512   K=2048  times=360       Time=961.058/2.669, 176.008/0.488ms     SpeedUp=5.46926         delta=0
M=32    N=512   K=256   times=1091      Time=439.023/0.402, 199.012/0.182ms     SpeedUp=2.20879         delta=0
M=32    N=512   K=32    times=3160      Time=407.022/0.128, 144.008/0.045ms     SpeedUp=2.84444         delta=0
M=32    N=64    K=2048  times=1091      Time=2863.17/2.624, 243.012/0.222ms     SpeedUp=11.8198         delta=0
M=32    N=64    K=256   times=3160      Time=1236.07/0.391, 229.011/0.072ms     SpeedUp=5.43056         delta=0
M=32    N=64    K=32    times=9010      Time=1085.06/0.12, 225.013/0.024ms      SpeedUp=5       delta=0
[1] run time: 17s.594ms.
PS D:\CPP\gemm_optimization\Release> .\gemm_optimization.exe /1 :verify 1 :clblas 1 :step 8
Compared with clBLAS, Verification enabled, Parallel disabled
[1] Hawaii  (kernels build: 437ms)
M=2048  N=512   K=2048  times=9         Time=279.019/31.002, 387.02/43.002ms    SpeedUp=0.720943        delta=0
M=2048  N=512   K=256   times=101       Time=419.026/4.148, 0/0ms       SpeedUp=inf     delta=0
M=2048  N=512   K=32    times=360       Time=280.01/0.777, 0.999/0.002ms        SpeedUp=388.5   delta=0
M=2048  N=64    K=2048  times=101       Time=571.03/5.653, 196.012/1.94ms       SpeedUp=2.91392         delta=0
M=2048  N=64    K=256   times=360       Time=270.015/0.75, 0.998/0.002ms        SpeedUp=375     delta=0
M=2048  N=64    K=32    times=1091      Time=207.01/0.189, 3/0.002ms    SpeedUp=94.5    delta=0
M=256   N=512   K=2048  times=101       Time=508.031/5.03, 0/0ms        SpeedUp=inf     delta=0
M=256   N=512   K=256   times=360       Time=243.011/0.675, 1/0.002ms   SpeedUp=337.5   delta=0
M=256   N=512   K=32    times=1091      Time=221.013/0.202, 2.998/0.002ms       SpeedUp=101     delta=0
M=256   N=64    K=2048  times=360       Time=955.057/2.652, 87.002/0.241ms      SpeedUp=11.0041         delta=0
M=256   N=64    K=256   times=1091      Time=422.022/0.386, 2.998/0.002ms       SpeedUp=193     delta=0
M=256   N=64    K=32    times=3160      Time=392.022/0.124, 9/0.002ms   SpeedUp=62      delta=0
M=32    N=512   K=2048  times=360       Time=946.056/2.627, 1.001/0.002ms       SpeedUp=1313.5  delta=0
M=32    N=512   K=256   times=1091      Time=435.025/0.398, 3/0.002ms   SpeedUp=199     delta=0
M=32    N=512   K=32    times=3160      Time=404.022/0.127, 7.993/0.002ms       SpeedUp=63.5    delta=0
M=32    N=64    K=2048  times=1091      Time=2845.16/2.607, 2.997/0.002ms       SpeedUp=1303.5  delta=0
M=32    N=64    K=256   times=3160      Time=1242.07/0.393, 9/0.002ms   SpeedUp=196.5   delta=0
M=32    N=64    K=32    times=9010      Time=1090.06/0.12, 23.001/0.002ms       SpeedUp=60      delta=0
[1] run time: 14s.813ms.
**2, Failed to support NVIDIA device. Commeningt out line 100 to line 105 still got other error:**
MIOpenGEMM   failed to compile kernel in Programs::update :                                                    ERROR (1)
MIOpenGEMM   Reporting an opencl error (MIOpenGEMM-hash: `building program in set_program_and_kernel') which   ERROR (2)
MIOpenGEMM    returned with cl_int -11 from function CL Compilation failed:                                    ERROR (3)
MIOpenGEMM   (buffer size = 425)  (buffer substring  : <kernel>:149:14: error: __kernel function cannot have   ERROR (4)
MIOpenGEMM    argument whose type is, or contains, type size_t                                                 ERROR (5)
MIOpenGEMM   const size_t a_offset,                                                                            ERROR (6)
MIOpenGEMM                ^                                                                                    ERROR (7)
MIOpenGEMM   <kernel>:151:14: error: __kernel function cannot have argument whose type is, or contains, type   ERROR (8)
MIOpenGEMM    size_t                                                                                           ERROR (9)
MIOpenGEMM   const size_t b_offset,                                                                            ERROR (10)
MIOpenGEMM                ^                                                                                    ERROR (11)
MIOpenGEMM   <kernel>:153:14: error: __kernel function cannot have argument whose type is, or contains, type   ERROR (12)
MIOpenGEMM    size_t                                                                                           ERROR (13)
MIOpenGEMM   const size_t c_offset,                                                                            ERROR (14)
MIOpenGEMM                ^                                                                                    ERROR (15)

**Comment by newling** [comment]
First, performance. Please try excluding the first GEMM call when timing, so move  

```
size_t time2 = MICROS(0);
```
in your file `gemm_opt.cpp' into the for loop,
```
if (j == 1) time2 = MICROS(0);
```

this will help because the first call with MIOpenGEMM compiles a kernel. MIOpenGEMM compiles a different kernel for all GEMM problems, unlike other projects which have a single (or a handful) of kernels for all GEMM problems. 

Second, NVIDIA. I changed `size_t` to `ulong` kernel args on branch `nvidia', I think this should fix it. I'll ping you when it's on master. I don't expect good performance on NVIDIA GPUs though.

**Comment by mz24cn** [comment]
You are right. Formal performance benchmark needs a warmup process. I revised the code and got such results as follows:
PS D:\CPP\gemm_optimization\Release> .\gemm_optimization.exe /1 :verify 1 :miopen 1 :step 8
Compared with MIOpenGemm, Verification enabled, Parallel disabled
[1] Hawaii  (kernels build: 443ms)
M=2048  N=512   K=2048  times=9         Time=279.016/31.001, 0/0ms      SpeedUp=inf     delta=0
M=2048  N=512   K=256   times=101       Time=421.025/4.168, 1.001/0.009ms       SpeedUp=463.111         delta=0
M=2048  N=512   K=32    times=360       Time=289.014/0.802, 5.002/0.013ms       SpeedUp=61.6923         delta=0
M=2048  N=64    K=2048  times=101       Time=548.035/5.426, 1.998/0.019ms       SpeedUp=285.579         delta=0
M=2048  N=64    K=256   times=360       Time=269.014/0.747, 4.999/0.013ms       SpeedUp=57.4615         delta=0
M=2048  N=64    K=32    times=1091      Time=213.013/0.195, 15.001/0.013ms      SpeedUp=15      delta=0
M=256   N=512   K=2048  times=101       Time=510.029/5.049, 2/0.019ms   SpeedUp=265.737         delta=0
M=256   N=512   K=256   times=360       Time=247.013/0.686, 3.998/0.011ms       SpeedUp=62.3636         delta=0
M=256   N=512   K=32    times=1091      Time=222.01/0.203, 15.001/0.013ms       SpeedUp=15.6154         delta=0
M=256   N=64    K=2048  times=360       Time=952.051/2.644, 6.001/0.016ms       SpeedUp=165.25  delta=0
M=256   N=64    K=256   times=1091      Time=425.023/0.389, 18.999/0.017ms      SpeedUp=22.8824         delta=0
M=256   N=64    K=32    times=3160      Time=393.022/0.124, 40.003/0.012ms      SpeedUp=10.3333         delta=0
M=32    N=512   K=2048  times=360       Time=964.054/2.677, 5.999/0.016ms       SpeedUp=167.312         delta=0
M=32    N=512   K=256   times=1091      Time=440.022/0.403, 14.999/0.013ms      SpeedUp=31      delta=0
M=32    N=512   K=32    times=3160      Time=403.021/0.127, 40.003/0.012ms      SpeedUp=10.5833         delta=0
M=32    N=64    K=2048  times=1091      Time=2863.16/2.624, 18.004/0.016ms      SpeedUp=164     delta=0
M=32    N=64    K=256   times=3160      Time=1234.07/0.39, 55.004/0.017ms       SpeedUp=22.9412         delta=0
M=32    N=64    K=32    times=9010      Time=1083.06/0.12, 116.005/0.012ms      SpeedUp=10      delta=0
[1] run time: 17s.752ms.
PS D:\CPP\gemm_optimization\Release> .\gemm_optimization.exe /1 :verify 1 :clblas 1 :step 8
Compared with clBLAS, Verification enabled, Parallel disabled
[1] Hawaii  (kernels build: 440ms)
M=2048  N=512   K=2048  times=9         Time=278.021/30.891, 0/0ms      SpeedUp=inf     delta=0
M=2048  N=512   K=256   times=101       Time=421.025/4.168, 0/0ms       SpeedUp=inf     delta=0
M=2048  N=512   K=32    times=360       Time=291.017/0.808, 0.995/0.002ms       SpeedUp=404     delta=0
M=2048  N=64    K=2048  times=101       Time=544.031/5.386, 0/0ms       SpeedUp=inf     delta=0
M=2048  N=64    K=256   times=360       Time=278.017/0.772, 0.998/0.002ms       SpeedUp=386     delta=0
M=2048  N=64    K=32    times=1091      Time=209.012/0.191, 2.999/0.002ms       SpeedUp=95.5    delta=0
M=256   N=512   K=2048  times=101       Time=509.033/5.039, 0/0ms       SpeedUp=inf     delta=0
M=256   N=512   K=256   times=360       Time=243.013/0.675, 1/0.002ms   SpeedUp=337.5   delta=0
M=256   N=512   K=32    times=1091      Time=220.011/0.201, 3/0.002ms   SpeedUp=100.5   delta=0
M=256   N=64    K=2048  times=360       Time=949.057/2.636, 0.999/0.002ms       SpeedUp=1318    delta=0
M=256   N=64    K=256   times=1091      Time=426.024/0.39, 2.998/0.002ms        SpeedUp=195     delta=0
M=256   N=64    K=32    times=3160      Time=399.023/0.126, 7.994/0.002ms       SpeedUp=63      delta=0
M=32    N=512   K=2048  times=360       Time=961.058/2.669, 0.998/0.002ms       SpeedUp=1334.5  delta=0
M=32    N=512   K=256   times=1091      Time=439.023/0.402, 2.998/0.002ms       SpeedUp=201     delta=0
M=32    N=512   K=32    times=3160      Time=403.022/0.127, 7.999/0.002ms       SpeedUp=63.5    delta=0
M=32    N=64    K=2048  times=1091      Time=2853.16/2.615, 3.998/0.003ms       SpeedUp=871.667         delta=0
M=32    N=64    K=256   times=3160      Time=1336.07/0.422, 7.999/0.002ms       SpeedUp=211     delta=0
M=32    N=64    K=32    times=9010      Time=1053.06/0.116, 23/0.002ms  SpeedUp=58      delta=0
[1] run time: 15s.33ms.

**Comment by mz24cn** [comment]
MIOpenGemm gets far better results. But clblas also gets better result to some extent. Obviously clblas also benifits from warmup. It is still the champion. Both MIOpen and clBLAS are supported by AMD. Since clBLAS is so nice, why AMD wanna develop a new gemm implementation? Does MIOpenGemm have better performance on new generation device such as Vega?

**Comment by newling** [comment]
These numbers seem unreliable. For example, you report for clBLAS

```

M=2048 N=512 K=2048 times=9 Time=279.016/31.001, 0/0ms SpeedUp=inf delta=0
M=2048 N=512 K=256 times=101 Time=421.025/4.168, 1.001/0.009ms SpeedUp=463.111 delta=0
M=2048 N=512 K=32 times=360 Time=289.014/0.802, 5.002/0.013ms SpeedUp=61.6923 delta=0

```

which implies 
1) increasing time with decreasing problem size (decreasing K) for clBLAS
2) M=2048 N=512 K=256 times=101 running in 1.001 ms is 54 teraflops

```
flops_per_millisecond = (2*2048*512*256*101)/1.001
flops_per_second = 10**3 * flops_per_millisecond
teraflops_per_second = 10**-12*flops_per_second = 54.2
```
this is impossible, there appears to a problem with your timing. You can consider the code at examples/deepbench.cpp to see how benchmarking can be done.

**Comment by newling** [comment]
> 2, Failed to support NVIDIA device. 

The (`size_t` -> `ulong`) change discussed above is merged into master now.

**Comment by mz24cn** [comment]
The performance result previously reported was wrong due to some code mistake when refactoring. Yestoday I released several benchmark results (https://mz24cn.github.io/gemm_optimization/). MIOpenGemm is partly better than clblas on some matrix sizes on NVIDIA hardware.

I have not updated miopengemm to latest code. Have you tested on NVIDIA hardware? I remember there is other error than size_t issue.

**Comment by newling** [comment]
Ran successfully on a K80 some months back, although much code has changed since then and it is likely that it no longer works. There are no plans to support NVIDIA in the near future, but feel free to contribute code to add support.
