### ISSUE TITLE
Not able to build on OSX

### ISSUE THREAD

**Issue by rgiduthuri** [ROCmSoftwarePlatform/MIOpenGEMM#2]
Here is the build log....

[  5%] Building CXX object tinygemm/CMakeFiles/tinygemm.dir/src/accuracytests.cpp.o
In file included from /Users/radha/github/tinygemm/tinygemm/src/accuracytests.cpp:1:
/Users/radha/github/tinygemm/tinygemm/include/tinygemm/accuracytests.hpp:69:22: error: call to 'abs' is ambiguous
      sum_l1_diff += std::abs(c_true_ij - c_ij);
                     ^~~~~~~~
/usr/include/stdlib.h:129:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:167:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:169:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^

**Comment by newling** [comment]
@rgiduthuri thanks.
