### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by jackyh** [ROCmSoftwarePlatform/MIOpenGEMM#20]
when I try to do cmake of MIOpenGEMM, got following error:

hcj@hcj:~/projects/miopengemm/MIOpenGEMM/build$ cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm ..
CMake Error at CMakeLists.txt:54 (find_package):
  Could not find a package configuration file provided by "OpenCL" with any
  of the following names:

    OpenCLConfig.cmake
    opencl-config.cmake

  Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
  "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/hcj/projects/miopengemm/MIOpenGEMM/build/CMakeFiles/CMakeOutput.log".

Anyone know why?

**Comment by newling** [comment]
Thanks for reporting. Have you installed the prerequisites listed in README.md? If so, where is OpenCL installed?

**Comment by jackyh** [comment]
I installed these files in the place that MIOpenGEMM can find. it gets passed:) Thanks to James! @newling
