### ISSUE TITLE
Possible bug in miog_beta.cl (generated kernel)

### ISSUE THREAD

**Issue by mattsinc** [ROCmSoftwarePlatform/MIOpenGEMM#35]
Hi @newling,

I've been having some problems with the miog_beta.cl kernel, which is generated by MIOpenGEMM (it is possible that #9 fixes this, I'm trying your suggestion from there now).  My tracing of the bug has led me back to something in the code I would like some clarification on.  Specifically, the part of the code I'm trying to understand is:

```
for (TSHORT i = 0; i < WORK_PER_THREAD; ++i){
      /* beta scaling */
      **if (beta <= 0 && beta >= 0)**{c[i] = 0;}else{c[i] *= beta;}
}
```

The part I'm trying to understand is starred above.  The only case where the if would be true is if beta (a float) is exactly 0.  But if the intent was to check if beta was 0, it would seem like there is a much simpler way to check for this (I realize that checking if a float is exactly 0 is frowned upon).

More broadly, I have two questions about MIOpenGEMM:

- Regardless of whether the above is a bug or not, how would I go about fixing it?  Where are these kernels being generated from within MIOpenGEMM?  Maybe in basegenerator.hpp and bylinegenerator.hpp?
    - EDIT: I see that the specific line in question is in betacgenerator.cpp, but would still appreciate some help understanding how this single line ties together with everything else.
- Is there a way to look at these OpenCL kernels directly in MIOpenGEMM?  So far the only way I've found to get the "original" source code is to force MIOpen to emit it before it compiles the kernel, but this is very manual and error prone.

Thanks,
Matt

**Comment by newling** [comment]
Hi Matt,

I think the beta >=0 && beta <= 0 line here was to prevent a compiler warning generated from beta == 0.0f (comparing floats is generally bad), I should comment this. 

As for viewing the generated kernels, take a look at examples/print.cpp

In GEMM, beta == 0 must be handled separately, as matrix C is allowed to contain nans and infs. For example if the user wants to set C = A*B, it should not be necessary for the user to first write valid floats to C. By having this branch in the code, the user does not need to worry about there being nans/infs in C before calling GEMM. 

James

**Comment by mattsinc** [comment]
Got it, thanks.

Matt
