### ISSUE TITLE
How can we test the half-precision performance in VEGA10-MI25?

### ISSUE THREAD

**Issue by BiranLi** [ROCmSoftwarePlatform/MIOpenGEMM#4]
In this version we can not test the half-precision performance。
How can we test the half-precision performance in VEGA10-MI25?

**Comment by dagamayank** [comment]
MIOpenGEMM does not support half-precision right now. Therefore, this is not an issue in MIOpenGEMM. We will share the info when half-precision is available. I am adding this as a feature request.
