### ISSUE TITLE
Incorrect results and hangs  

### ISSUE THREAD

**Issue by newling** [ROCmSoftwarePlatform/MIOpenGEMM#9]
(On ROCm 1.6)

1) Certain combinations of HyPas (kernel parameters) and Geometry (GEMM dimensions) give incorrect final C. 

2) Certain HyPas result in compiler hangs, often when macro-tile has height=1 or width=1.

Both problems 1 and 2 go away when ```export AMD_OCL_BUILD_OPTIONS_APPEND="-cl-opt-disable"``` is used, so these problems appear to be unrelated to MIOpenGEMM. An issue has been opened here https://github.com/RadeonOpenCompute/ROCm/issues/178

I've tried to shield final API users from the problem, but it's difficult to determine exactly what the problem parameter combinations are, so there may be a few bad cases exposed. If you think you have found a bad case, please check by using code in examples/accu.cpp, with and without `export AMD_OCL_BUILD_OPTIONS_APPEND="-cl-opt-disable"`.

Some problem cases I've observed are listed in examples/genrocmtest.cpp

**Comment by mattsinc** [comment]
@newling, I am encountering some issues with ROCm 1.6 that may be resolved by this.  A quick question: does this solution assume that the MIOpenGEMM kernels have not already been generated and placed in the ~/.cache/miopen/... folder?

Thanks,
Matt

**Comment by newling** [comment]
This compiler issue has been resolved in ROCm now.
